name: clash-issue1686

custom-setup:
  dependencies:
    - base
    - Cabal
    - clashilator

dependencies:
  - base >= 4.7 && < 5
  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  # - bytestring
  # - mtl
  # - transformers
  # - array
  # - lens
  # - barbies
  # - barbies-th
  # - tuple
  # - split
  # - extra
  # - template-haskell

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

source-dirs: src

executables:
  exe1:
    main: main.hs
    verbatim:
      x-clashilator-top-is: Hardware.Compucolor2
      x-clashilator-entity: simEntity
      x-clashilator-clock: CLK_40MHZ

  exe2:
    main: main.hs
    verbatim:
      x-clashilator-top-is: Hardware.Compucolor2
      x-clashilator-entity: simEntity
      x-clashilator-clock: CLK_40MHZ
